# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-28 08:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=64, verbose_name='接口测试用例名称')),
                ('case_priority', models.IntegerField(default=1, verbose_name='测试用例优先级')),
                ('case_title', models.CharField(max_length=128, verbose_name='测试用例标题')),
                ('case_url', models.CharField(max_length=255, verbose_name='测试用例地址')),
                ('case_header', models.CharField(max_length=255, verbose_name='测试用例header')),
                ('case_parameters', models.CharField(max_length=255, verbose_name='测试用例参数')),
                ('case_method', models.CharField(max_length=64, verbose_name='测试用例请求方式')),
                ('case_expect', models.CharField(max_length=1024, verbose_name='测试用例期望值')),
                ('case_execute_result', models.CharField(max_length=4096, verbose_name='测试用例执行结果')),
                ('case_create_username', models.CharField(max_length=64, verbose_name='测试用例创建者')),
                ('case_execute_username', models.CharField(max_length=64, verbose_name='测试用例执行人')),
                ('case_execute_time', models.DateTimeField(default=datetime.datetime(2019, 8, 28, 16, 8, 37, 178799), verbose_name='测试用例执行时间')),
                ('case_status', models.IntegerField(choices=[(1, '执行成功'), (2, '执行失败')], verbose_name='测试用例状态')),
            ],
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='model_name',
            field=models.CharField(default='', max_length=255, verbose_name='模块名称'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='model_num',
            field=models.CharField(default='', max_length=255, verbose_name='模块编号'),
        ),
        migrations.AddField(
            model_name='itc',
            name='case_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ProjectModel', verbose_name='接口测试用例名称'),
        ),
    ]
