# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-28 09:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190828_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItcResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_execute_pass', models.IntegerField(choices=[(1, '待定'), (2, '已通过'), (3, '未通过')], verbose_name='测试用例执行是否通过')),
                ('case_execute_status', models.IntegerField(choices=[(1, '未执行'), (2, '已执行')], verbose_name='测试用例状态')),
                ('case_execute_time', models.DateTimeField(default=datetime.datetime(2019, 8, 28, 17, 13, 22, 536427), verbose_name='测试用例执行时间')),
            ],
        ),
        migrations.RemoveField(
            model_name='itc',
            name='case_execute_time',
        ),
        migrations.RemoveField(
            model_name='itc',
            name='case_status',
        ),
        migrations.AlterField(
            model_name='itc',
            name='case_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ProjectModel', verbose_name='接口测试用例所属模块'),
        ),
    ]
