# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-29 07:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190828_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itc',
            name='case_name',
        ),
        migrations.AlterField(
            model_name='itcresult',
            name='case_execute_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 29, 15, 41, 44, 91224), verbose_name='测试用例执行时间'),
        ),
    ]
