# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-29 09:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190829_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itc',
            name='case_execute_result',
        ),
        migrations.AlterField(
            model_name='itcresult',
            name='case_execute_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 29, 17, 44, 28, 68859), verbose_name='测试用例执行时间'),
        ),
    ]
