# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-29 09:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20190829_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itcresult',
            name='case_execute_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 29, 17, 45, 43, 981341), verbose_name='测试用例执行时间'),
        ),
    ]
