# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-02 08:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20190829_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='itc',
            name='case_execute_result',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='web.ItcResult'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itcresult',
            name='case_execute_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 16, 31, 18, 775870), verbose_name='测试用例执行时间'),
        ),
    ]
