# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-02 08:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20190902_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itc',
            name='case_execute_result',
        ),
        migrations.AddField(
            model_name='itc',
            name='case_execute_pass',
            field=models.IntegerField(choices=[(1, '待定'), (2, '已通过'), (3, '未通过')], default=3, verbose_name='测试用例执行是否通过'),
        ),
        migrations.AddField(
            model_name='itc',
            name='case_execute_status',
            field=models.IntegerField(choices=[(1, '未执行'), (2, '已执行')], default=1, verbose_name='测试用例状态'),
        ),
        migrations.AddField(
            model_name='itc',
            name='case_execute_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 16, 44, 11, 524053), verbose_name='测试用例执行时间'),
        ),
        migrations.DeleteModel(
            name='ItcResult',
        ),
    ]
