# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-03 01:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20190902_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='itc',
            name='case_execute_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 3, 9, 3, 24, 488400), verbose_name='测试用例执行时间'),
        ),
    ]
