# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-03 01:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20190903_0903'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Testss',
        ),
        migrations.AlterField(
            model_name='itc',
            name='case_execute_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 3, 9, 9, 49, 373462), verbose_name='测试用例执行时间'),
        ),
    ]
