# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-25 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20190903_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itc',
            name='case_execute_pass',
            field=models.IntegerField(choices=[(1, '待定'), (2, '已通过'), (3, '未通过')], default=1, verbose_name='测试用例执行是否通过'),
        ),
        migrations.AlterField(
            model_name='itc',
            name='case_execute_time',
            field=models.DateTimeField(default='2019-09-25 10:06:55', verbose_name='测试用例执行时间'),
        ),
        migrations.AlterField(
            model_name='projectmanage',
            name='project_status',
            field=models.IntegerField(choices=[(1, '未执行'), (2, '已执行')], default=1, verbose_name='项目状态'),
        ),
        migrations.AlterField(
            model_name='testss',
            name='name',
            field=models.TextField(max_length=64),
        ),
    ]
