# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-15 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20191015_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='testss',
            name='med',
            field=models.ImageField(blank=True, upload_to='ui/%Y%M%D'),
        ),
        migrations.AlterField(
            model_name='itc',
            name='case_execute_time',
            field=models.DateTimeField(default='2019-10-15 09:56:27', verbose_name='测试用例执行时间'),
        ),
    ]
