# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-15 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20191015_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itc',
            name='case_execute_time',
            field=models.DateTimeField(default='2019-10-15 11:10:17', verbose_name='测试用例执行时间'),
        ),
        migrations.AlterField(
            model_name='testss',
            name='med',
            field=models.FileField(upload_to='ui/'),
        ),
    ]
