# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-17 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_auto_20191015_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='itc',
            name='case_desc',
            field=models.CharField(default='', max_length=256, verbose_name='用例描述信息'),
        ),
        migrations.AlterField(
            model_name='itc',
            name='case_execute_time',
            field=models.DateTimeField(default='2019-10-17 18:30:24', verbose_name='测试用例执行时间'),
        ),
    ]
