# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-21 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_auto_20191018_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testss',
            name='med',
        ),
        migrations.AlterField(
            model_name='itc',
            name='case_execute_time',
            field=models.DateTimeField(default='2019-10-21 15:48:15', verbose_name='测试用例执行时间'),
        ),
        migrations.AlterField(
            model_name='testss',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
