# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-25 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20190925_1132'),
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uicase',
            name='case_code',
            field=models.TextField(default='', verbose_name='用例代码'),
        ),
        migrations.AddField(
            model_name='uicase',
            name='case_create_username',
            field=models.CharField(default='', max_length=64, verbose_name='测试用例创建者'),
        ),
        migrations.AddField(
            model_name='uicase',
            name='case_execute_pass',
            field=models.IntegerField(choices=[(1, '待定'), (2, '已通过'), (3, '未通过')], default=1, verbose_name='测试用例执行是否通过'),
        ),
        migrations.AddField(
            model_name='uicase',
            name='case_execute_status',
            field=models.IntegerField(choices=[(1, '未执行'), (2, '已执行')], default=1, verbose_name='测试用例状态'),
        ),
        migrations.AddField(
            model_name='uicase',
            name='case_execute_time',
            field=models.DateTimeField(default='2019-09-25 11:32:15', verbose_name='测试用例执行时间'),
        ),
        migrations.AddField(
            model_name='uicase',
            name='case_execute_username',
            field=models.CharField(default='', max_length=64, verbose_name='测试用例执行人'),
        ),
        migrations.AddField(
            model_name='uicase',
            name='case_name',
            field=models.CharField(default='UI demo', max_length=64, verbose_name='用例名称'),
        ),
        migrations.AddField(
            model_name='uicase',
            name='case_priority',
            field=models.IntegerField(default=1, verbose_name='测试用例优先级'),
        ),
        migrations.AddField(
            model_name='uicase',
            name='case_vest_project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.ProjectManage', verbose_name='归属项目'),
        ),
    ]
