# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-12 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_auto_20190925_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uicase',
            options={'ordering': ['-case_execute_time']},
        ),
        migrations.AlterField(
            model_name='uicase',
            name='case_create_username',
            field=models.CharField(default='好心人', max_length=64, verbose_name='测试用例创建者'),
        ),
        migrations.AlterField(
            model_name='uicase',
            name='case_execute_time',
            field=models.DateTimeField(default='2019-10-12 14:27:35', verbose_name='测试用例执行时间'),
        ),
        migrations.AlterField(
            model_name='uicase',
            name='case_execute_username',
            field=models.CharField(default='好心人', max_length=64, verbose_name='测试用例执行人'),
        ),
    ]
