# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-15 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0006_auto_20191015_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uicase',
            name='case_execute_time',
            field=models.DateTimeField(default='2019-10-15 09:56:27', verbose_name='测试用例执行时间'),
        ),
        migrations.AlterField(
            model_name='uicase',
            name='case_media_report',
            field=models.ImageField(blank=True, upload_to="ui/b'\\xf1\\xc6\\xc7X2\\xc1\\x12t\\x1et\\xf5\\x83*\\x94\\x1f\\x96'.mp4"),
        ),
    ]
