# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-15 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0007_auto_20191015_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uicase',
            name='case_execute_time',
            field=models.DateTimeField(default='2019-10-15 10:52:46', verbose_name='测试用例执行时间'),
        ),
        migrations.AlterField(
            model_name='uicase',
            name='case_media_report',
            field=models.ImageField(blank=True, upload_to="ui/b'l\\xa4\\xe22W\\x98\\x17]\\x16\\xb7H\\xa5\\x06E\\x98\\x8c'.mp4"),
        ),
    ]
