# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-15 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0009_auto_20191015_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uicase',
            name='case_execute_time',
            field=models.DateTimeField(default='2019-10-15 11:10:17', verbose_name='测试用例执行时间'),
        ),
        migrations.AlterField(
            model_name='uicase',
            name='case_media_report',
            field=models.ImageField(blank=True, upload_to="ui/b'\\x0f\\x08L+JzL\\xcfz\\x02\\xa7\\xd3\\xbf\\xde\\x92]'.mp4"),
        ),
    ]
