# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-15 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0010_auto_20191015_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uicase',
            name='case_execute_time',
            field=models.DateTimeField(default='2019-10-15 11:10:50', verbose_name='测试用例执行时间'),
        ),
        migrations.AlterField(
            model_name='uicase',
            name='case_media_report',
            field=models.ImageField(blank=True, upload_to="ui/b'\\xf6V\\xe6\\xe8a\\x19\\x0eFUz:\\xd2\\xea\\xb1\\x8c\\x87'.mp4"),
        ),
    ]
