# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-15 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0011_auto_20191015_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uicase',
            name='case_execute_time',
            field=models.DateTimeField(default='2019-10-15 16:50:32', verbose_name='测试用例执行时间'),
        ),
        migrations.AlterField(
            model_name='uicase',
            name='case_media_report',
            field=models.FileField(blank=True, default='', upload_to='ui/', verbose_name='视频结果目录'),
        ),
    ]
