# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-17 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0013_auto_20191016_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uicase',
            name='case_execute_time',
            field=models.DateTimeField(default='2019-10-17 18:30:24', verbose_name='测试用例执行时间'),
        ),
    ]
