# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-15 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0006_auto_20191015_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apmcase',
            name='case_execute_time',
            field=models.DateTimeField(default='2019-10-15 11:09:40', verbose_name='测试用例执行时间'),
        ),
    ]
