# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-16 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0010_auto_20191015_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='apmcase',
            name='case_media_report',
            field=models.CharField(default='', max_length=64, verbose_name='MP4版的测试报告'),
        ),
        migrations.AlterField(
            model_name='apmcase',
            name='case_execute_time',
            field=models.DateTimeField(default='2019-10-16 18:59:23', verbose_name='测试用例执行时间'),
        ),
    ]
